version: '2'

# NOTE env vars UID, GID, USERNAME, FQDN are set/exported in .bashrc

volumes:
    conf:
    vhost:
    html:
    certs:
    acme:

services:
  jupyter:
    build:
      context: images/pytorch-jupyter-gpu
      args:
        - PYTORCH_VERSION=1.7.0-cuda11.0-cudnn8-runtime
        - LOCALE=en_US.UTF-8
        - NB_USER=${USERNAME}
        - NB_UID=${UID}
        - NB_GID=${GID}
    container_name: pytorch-jupyter-gpu
    user: "${UID}:${GID}"
    volumes:
      - /home/notebooks:/home/notebooks
    environment:
      - VIRTUAL_HOST=${FQDN}
      - LETSENCRYPT_HOST=${FQDN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    network_mode: bridge
    restart: always
    deploy: # requires minimum docker-compose v1.28
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu

  nginx-proxy:
    build: images/nginx/
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - jupyter
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: nginx-le
    volumes_from:
        - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
    network_mode: bridge
    restart: always

