version: '2'

services:
    jupyter:
        build:
            context: images/pytorch-jupyter-gpu
            args:
                - PYTORCH_VERSION=1.6.0-cuda10.1-cudnn7-runtime
                - PYTORCH_GEOMETRIC_VERSION=1.6.0+cu101
                - LOCALE=en_US.UTF-8
                - NB_USER=${USERNAME}
                - NB_UID=${UID}
                - NB_GID=${GID}
        container_name: jupyter
        hostname: jupyter
        user: "${UID}:${GID}"
        environment:
            - VIRTUAL_HOST=${FQDN}
        volumes:
            - /mas:/mas
            - /u:/u
            - /tmp:/tmp
            - /dtmp:/dtmp
        networks:
            - stack
        restart: always
        deploy: # requires minimum docker-compose v1.28
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu

    nginx-proxy:
        build: images/nginx-proxy/
        container_name: nginx
        hostname: nginx
        ports:
            - "${UID}:443"
        depends_on:
            - jupyter
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - stack
        restart: always

networks:
    stack:
        driver: bridge

