version: '2'

services:
    jupyter:
        build:
            context: images/pytorch-jupyter-gpu
            args:
                - NB_USER=${USERNAME}
                - NB_UID=${UID}
                - NB_GID=${GID}
        container_name: jupyter
        hostname: jupyter
        user: "${UID}:${GID}"
        volumes:
            - /home:/hosthome
        networks:
            - stack
        shm_size: '8gb'
        restart: always
        deploy: # requires minimum docker-compose v1.28
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu

    nginx-proxy:
        build: images/nginx-proxy/
        container_name: nginx
        hostname: nginx
        ports:
            - "127.0.0.1:443:443"
            - "127.0.0.1:6006:6006"
        environment: # this and both values under ports should be the same
            - TENSORBOARD_PORT=6006
        depends_on:
            - jupyter
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - stack
        restart: always

    postgres:
        build:
            context: images/postgres/
            args:
                - POSTGRES_VERSION=12.6
                - POSTGIS_VERSION=postgresql-12-postgis-3
                - NB_UID=${UID}
                - NB_GID=${GID}
        container_name: postgres
        hostname: postgres
        user: "${UID}:${GID}"
        environment:
            - PGDATA=/hosthome/${USERNAME}/data/postgresql/12/main
            - POSTGRES_PASSWORD_FILE=/home/postgres/pw
        volumes:
            - /home:/hosthome
        networks:
            - stack
        restart: always

networks:
    stack:
        driver: bridge

